### ISSUE TITLE
Kerning seems broken

### ISSUE THREAD

**Issue by SenpaiSharp** [FontStashSharp/FontStashSharp#47] opened 2022-07-24 22:49 UTC
Kerning doesn't seem to be working correctly in the latest versions. 

Version 1.0, Correct:
![correct](https://user-images.githubusercontent.com/36146858/180668835-d247d404-12f3-45ad-a50c-97fe2d8d76e7.png)

Version 1.1.6, Incorrect:
![notcorrect](https://user-images.githubusercontent.com/36146858/180668837-b9e97157-853a-4206-98a1-58bcbbdfa21d.png)

I'm strictly guessing that it happened somewhere around here 
https://github.com/FontStashSharp/FontStashSharp/commit/41aeb74b44c594abefaef3cdd27ec70dfe6bed2e but I haven't the time to check at the moment.

**Comment by SenpaiSharp** [comment] 2022-07-25 15:45
I think the kerning properly affects the position of the following letters (esday) but not the u itself. I fixed this exact same problem before in Monogame.Extended but the logic is a little different so I need to think this out. https://github.com/craftworkgames/MonoGame.Extended/pull/465

**Comment by SenpaiSharp** [comment] 2022-07-25 16:36
Yes, pretty sure the order of things needs some changing. I think the original code factored kerning into the Glyph's advance, so the drawing was correct. Now, calculating the advance happens after the draw. We need to get the kerning data before that happens.

**Comment by SenpaiSharp** [comment] 2022-07-25 17:42
> SpriteFontBase.IFontStashRenderer.cs

```
//HACK:  

                /* [Kerning Fix]
                 * With kerning enabled, the letters following a kerning pair are positioned correctly 
                 * but the current char of the kerning pair is not because the XAdvance is calculated 
                 * after it is being drawn.
                 */

                // Get the Advance now, before we apply it to pos.
                var one = GetXAdvance(glyph, prevGlyph);
                // Get the Advance that would happen as if there was no kerning.
                var two = GetXAdvance(glyph, null);
                // Get the difference. In the case of there being no kerning anyway, it will be 0.
                var difference = one - two;

                if (!glyph.IsEmpty)
		{
			color = source.GetNextColor();
			// Offset with kerning difference before drawing.
			var p = pos + new Vector2(glyph.RenderOffset.X + difference, glyph.RenderOffset.Y);
			p = p.Transform(ref transformation);

			renderer.Draw(glyph.Texture,
				p,
				glyph.TextureRectangle,
				color,
				rotation,
				scale,
				layerDepth);
		}

                // Add the proper XAdvance that we already calculated.
		pos.X += one;
		prevGlyph = glyph;
```

This kludge code will fixes the problem

Without

![notcorrect2](https://user-images.githubusercontent.com/36146858/180837903-d83eaeb0-9db6-4c72-893b-4fa1ec305037.png)

With

![correct2](https://user-images.githubusercontent.com/36146858/180837947-8d28ca63-20da-4038-a196-e6fe8ba17de1.png)

but I can't imagine it's the ideal solution, so I'm not going to PR yet. As things are currently set up, the calculation of the kerning is always going to come one cycle late. The following letters will be in spaces they should be but not the second part of the pair. Getting the kerning before the draw and applying it to the position is needed but kerning isn't part of the base class SpriteFontBase. If this is wanted to be kept, then adding an out modifier to the abstract GetXAdvance method could maybe work?

`internal abstract float GetXAdvance(FontGlyph glyph, FontGlyph prevGlyph, out float modifier);`

And simply ignore the modifier when it isn't needed?

I think SpriteFontBase.cs InternalTextBounds probably needs a fix with this too, in the event that a kerning pair comes at the end of a string. Will look into.

**Comment by SenpaiSharp** [comment] 2022-07-25 18:08
> I think SpriteFontBase.cs InternalTextBounds probably needs a fix with this too, in the event that a kerning pair comes at the end of a string. Will look into.

Actually, this might be fine because this is an order of operations issue; it seems ITB isn't affected. In fact, it can be used to more clearly demonstrate where the rendering part is messed up.

Without hack

![notcorrect3](https://user-images.githubusercontent.com/36146858/180844707-0b7684d2-120d-4237-9383-0683ff5d4a05.png)

With hack

![correct3](https://user-images.githubusercontent.com/36146858/180844851-4a669b5a-571a-4730-8b25-91cb1604542f.png)

**Comment by SenpaiSharp** [comment] 2022-07-25 18:31
The out modifier change would work, it's just ugly in the face of a lack of a solution (that I can come up with). It avoids having to calculate twice, which cost and probably has some edge case weirdnesses somewhere. I'm currently discarding it everywhere except for  If there's a way to get the kerning information before drawing without breaking up the rest of the code's flow, that would be ideal but I'm not seeing it. Perhaps I am over thinking things.

**Comment by rds1983** [comment] 2022-07-28 11:50
What ttf is used?

**Comment by SenpaiSharp** [comment] 2022-07-28 13:09
> What ttf is used?

https://www.dafont.com/komika-text.font

**Comment by SenpaiSharp** [comment] 2022-07-28 13:21
I've experimented with doing XAdvance prior to the, draw along with running a check to not advance if previous glyph was null. This created a whole host of new spacing issues that I have not been able to crack down on why they're happening.

![Untitled](https://user-images.githubusercontent.com/36146858/181514234-8eb3aeac-e7d0-4c69-aabf-4998f4231d24.png)

I think my initial solution was probably the most effective while least disruptive path. I realized I was overthinking doing two XAdvance calculations, getting the XAdvance from the glyph to calculate the kerning difference is sufficient.  

If you want to go that route, I could clean my solution up, write it in a fairly kerning agnostic way and comment the code to explain the thinking behind it.

**Comment by rds1983** [comment] 2022-07-28 15:54
Please, test whether the issue is fixed in 1.1.7

**Comment by SenpaiSharp** [comment] 2022-07-28 23:59
Looks good so far. Going to poke into it a bit.

![result](https://user-images.githubusercontent.com/36146858/181656306-662485fb-327c-4ba4-b3ef-7b98aac6ccbb.png)

**Comment by SenpaiSharp** [comment] 2022-07-29 00:39
Yes, this seems correct. It follows what I thought should be done with my last attempts but it doesn't produce the spacing issues I was having. I think I was inadvertently applying the kerning twice.

**Closed** 2022-07-29 00:40 UTC
